spring.application.name=spring_boot_backend
#Tomcat server port number 8080
#server.port=8081
#context path default value : empty
#server.servlet.context-path=/ems
#server.servlet.session.persistent=false
#DB properties
spring.datasource.url=jdbc:mysql://localhost:3306/e_commerce_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=manager
# JPA properties
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
#logging.level.org.springframework.orm.hibernate5=DEBUG
spring.security.jwt.secret.key=93df9b0e51237a3cc2823912ef0cebcf424cf14c84a3a830e047d273d7c558530f563718d096bb306a1bfc90a9d102ca6a475bbbcbcddcfb20989687a81ada6a
spring.security.jwt.exp.time=18000000